<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Label="Globals">
		<SccProjectName>SAK</SccProjectName>
		<SccProvider>SAK</SccProvider>
		<SccAuxPath>SAK</SccAuxPath>
		<SccLocalPath>SAK</SccLocalPath>
	</PropertyGroup>
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net472;net8.0</TargetFrameworks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="OpcLabs.EasySparkplug" Version="5.84.187"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Library\SparkplugEdgeNodeDemoLibrary\SparkplugEdgeNodeDemoLibrary.vbproj"/>
	</ItemGroup>
</Project>
